strimzi/strimzi.github.io

_data/menu.yml
roadmap/index.md

I though it would be useful to have a roadmap on the Strimzi website. Please review.

Add Roadmap page

---

index.md

This PR improves the Contributing section of the website with the infor which we already have in the README.md file in the `strimzi` repo. I think it would be good to have this info also on the website if someone starts there. WDYT?

Improve the Contributing section of the website

---

index.md

This PR should address the issue strimzi/strimzi#356

Add Downloads section to Strimzi page

---

roadmap/index.md

This PR updates the Roadmap page to reflect the work done / planned for the release 0.4.0.

Update Roadmap to reflect work done / planned for 0.4.0

---

_posts/2018-05-17-running-strimzi-on-openshift-online.md

This PR adds a new blog post called "Running Stirmzi on OpenShift Online".

Add blog post about running Strimzi on OSO

---

presentations/index.md

links to video and slides by Tom Bentley (Red Hat) from talk at OpenShift Commons Operator Framework SIG meeting July 20, 2018

added link to Strimzi Operator talk

---

roadmap/index.md

The roadmap is currently a bit of a mess. But this should give an update for 0.5.0 and an idea about 0.6.0.

Update the roadmap

---

_posts/2018-07-30-running-kafka-on-dedicated-nodes.md
_posts/2018-XX-XX-running-kafka-on-dedicated-nodes.md

This is a new blog post to be published after the 0.5.0 release. It talks about Affinity and Tolerations and about setting up dedicated nodes for Apache Kafka.
I would appreciate your review.

Running Kafka on dedicated Kubernetes nodes

---

_includes/disqus.html
_layouts/post.html

This PR is for addressing #24 and allowing people to engage with the Strimzi community on the web site through comments on blog posts.

Added Disqus for comments support on blog posts

---

_posts/2018-08-20-strimzi-0.6.0-release.md
_posts/2018-08-XX-strimzi-0.6.0-release.md

This PR is for the blog post about coming 0.6.0 release.
Of course, we have to merge it after the release will be out :-)

Strimzi 0.6.0 release

---

_includes/header.html

Inserting Google Analytics Tag to begin site traffic analysis

Adding Google Analytics Tag to Header

---

_posts/2018-10-01-strimzi-0.7.0-release.md

This PR is about a blog post on 0.7.0 release.
Because we are late on that and we are closed to the new 0.8.0 release, I focused on the two main features (exposing Kafka outside and SCRAM SHA auth) but just referring to the others.
I don't think we have to spend so much time on it, I'd like to publish it tomorrow morning.
Anyway, any grammar or content feedback is welcome!

Strimzi 0.7.0 release blog post

---

_data/authors.yml
_posts/2018-10-30-using-helm.md
_posts/2018-11-01-using-helm.md

As requested, this blog post explains how to use the Strimzi Kafka Operator Helm Chart in various use cases.
/cc @ppatierno

Helm blog post

---

_posts/2018-11-16-using-vault-with-strimzi.md

@ppatierno Added corrections according to latest learnings. 🍂

Update Vault blog to include information about the CA chain

---

_posts/2018-12-23-strimzi-0.9.0-release.md

NOTE: most of the maintenance time windows feature comes from doc where it was well explained

Added blog post about 0.9.0 release

---

_posts/2019-03-01-resizing-persistent-volumes.md

This PR adds a blog post about resizing Strimzi persistent volumes on OpenShift 4.

Add blog post about storage resizing

---

_posts/2020-03-06-strimzi-and-operator-lifecycle-manager.md

The core of this blog post are the two youtube videos. I'm not sure I'm completely happy about the text, which is just supposed to be some wrapper for the videos. If you have any better ideas or suggestion let me know.

Add blog post about OLM and Operator Hub

---

quickstarts/minikube/index.md
quickstarts/okd/index.md

Fixes https://github.com/strimzi/strimzi.github.io/issues/54

Fixed mismatch between text and yaml

---

quickstarts/minikube/index.md
quickstarts/okd/index.md

As a quickstart, not sure one really needs a full cluster w/ 3 nodes for ZK, and K

For initial start the single node example should be good enough

---

quickstarts/minikube/index.md
quickstarts/okd/index.md

follow-up for #56  
and do some cosmetics, by adding some better desc. to actually match the cluster setup
/cc @scholzj

Missed some doc to match the simple cluster setup

---

presentations/index.md

Added presentation from "Modern Integration and Application Development

---

_data/authors.yml
_layouts/post.html
presentations/index.md

Here's the presentation.
WDYT about the addition I made to include blog author's websites?  This is helpful for SEO back to some presence for the author, in my case I'm trying to boost my website, not just my twitter.

Kafka in Jail with Strimzi presentation and author SEO on blogs

---

_data/releases.yaml
documentation/archive/index.md
documentation/index.md
downloads/archive/index.md
downloads/index.md
index.md
quickstarts/minikube/index.md
quickstarts/okd/index.md

As previously discussed, this should make updating the site when a new version is released somewhat simpler.

Use templating for versions

---

_posts/2019-03-01-resizing-persistent-volumes.md
_posts/2019-07-08-persistent-storage-improvements.md

In 0.12.0 we had a lot of improvements to the persistent storage such as:
* Resizing
* Adding / removing JBOD volumes
* Storage class overrides
This blog post summarises the improvements.

Add blog post about persistent storage improvements in 0.12.0

---

_posts/2019-07-22-http-bridge-intro.md

Improved grammar and language. Tried to incorporate Jakub's comments where possible.

reworked Paolo's blog post

---

documentation/archive/index.md

Fixed links to bridge archived docs

---

_posts/2019-09-30-whats-new-in-strimzi-0.14.0.md

This blog post gives an introduction to all the new stuff in 0.14.0 release.

Add blog post about what's new in 0.14.0

---

_posts/2019-09-30-whats-new-in-strimzi-0.14.0.md

This Pr fixes simple typo in the 0.14.0 introduction blog post.

Fix typo in the 0.14.0 introduction blog post

---

docs/0.14.0/0.14.0.html
docs/0.14.0/full.html
docs/latest/full.html
docs/latest/latest.html

Thsi PR should add the docs parts which were missing at release time such as OAuth, Tracing, Kafka Exporter etc.

Update the 0.14.0 documenttion with the parts which were not ready at release time

---

_posts/2019-11-17-strimzi-at-kubecon-san-diego.md
_posts/2019-11-18-strimzi-at-kubecon-san-diego.md

This PR adds the blog post about Strimzi presence at KubeCOn in San Diego.

Write blog post about Strimzi at KubeCon in San Diego

---

_posts/2019-12-20-festive-message.md

Signed-off-by: Simon Woodman <swoodman@redhat.com>

Initial version of festive blog post

---

_posts/2019-11-01-deploying-debezium-with-kafkaconnector-resource.md

Add blog Debezium connector blog

---

_redirects

This PR adds a new redirect for the examples YAML files.

Add redirects for examples

---

quickstarts/index.md
quickstarts/kind/index.md

Signed-off-by: Marko Strukelj <marko.strukelj@gmail.com>

Add Kubernetes Kind instructions

---

_includes/homepage/homepage-hero-band.html

This PR fixes the link to a "what is an operator" article.

Fixed link to what is an operator

---

_sass/strimzi.scss

Try to fix the code font in the Reference APi headers.

Try to fix documentation headers

---

_data/presentations.yaml

This PR adds the talk I had with Otavio about Kafka, Cmale and Strimzi to the list of presentations.

Add talk from DevConf.CZ 2020 about Kafka, Camel and Strimzi connector operator to presentations

---

_posts/2020-04-15-develop-apache-kafka-applications-with-strimzi-and-minikube.md

Apart from having the video on the YouTube channel, I thought it might be useful to aslo add it as blog post to get it into people's RSS readers etc.

Add video blog post abotu developing Kafka apps with Strimzi

---

_data/presentations.yaml

Signed-off-by: Simon Woodman <swoodman@redhat.com>

Added card for Jakub's introduction to Strimzi video

---

_includes/site-header.html

Signed-off-by: Adela Sofia Arreola <adelaarreola@gmail.com>

Updates GA tracking code

---

quickstarts/kind.md

use deploymet approach instead of doing grep.

update logs command to use deployment

---

_includes/project-footer.html
_sass/includes/project-footer.scss

Doesn't look super great. Maybe someone who's more acquainted with the site's CSS can follow up and make it look better.

Update copyright footer

---

_includes/site-header.html
_includes/site-scripts.html

Removes Adobe Analytics Tracking from site header and scripts sections.

Removes Adobe Analytics Tracking

---

_layouts/post.html

Signed-off-by: Paolo Patierno <ppatierno@live.com>

Added link to author Twitter handle where applicable

---

_posts/2020-05-14-mirror-kafka-eventhub.md

Signed-off-by: Paolo Patierno <ppatierno@live.com>

Added link to the new MM2 blog post

---

Gemfile.lock
_sass/core/global.scss
_sass/includes/toc.scss
_sass/layouts/default.scss
_sass/strimzi.scss
assets/css/main.scss

[ENTMQST-1959](https://issues.redhat.com/browse/ENTMQST-1959) Updates the styles applied to the Strimzi documentation to improve the presentation.
Signed-off-by: Adela Sofia Arreola <adelaarreola@gmail.com>

Updates documentation styles

---

_data/authors.yml
_posts/2019-08-08-hacking-for-cruise-control.md
_posts/2020-06-05-cruise-control.md

This PR add a blog post on Strimzi's native support for Cruise Control.

Cruise Control blog post

---

_includes/header-navigation.html
_includes/project-footer.html

This PR adds YouTube icon and link to the top navigation menu and to the footer.

Add YouTube icon and link to the top and bottom navigation menu

---

_includes/community/community-contributions-band.html
_includes/homepage/homepage-announcement-band.html
_includes/homepage/homepage-zoom-band.html
_layouts/index.html
_sass/strimzi.scss
assets/images/community/community_icon_zoom.svg
assets/images/zoom_icon.svg

home page... added code for announcement band for survey (with blue or orange background) and zoom meeting band. Added zoom meeting to community page too.
https://issues.redhat.com/browse/DESIGN-1985

Add announcement and zoom meeting band

---

_includes/community/community-contributions-band.html
_includes/homepage/homepage-zoom-band.html

This PR set the link to the Zoom meetings minute that provides information for joining the two date/time we use for the community meeting.

Added link to Zoom meeting information

---

_data/authors.yml
_posts/2020-09-07-introduction-to-system-tests.md
_posts/2020-09-21-introduction-to-system-tests.md

This PR adding blog post about `Instroduction to our system tests module`. Moreover, illustrates the idea why we should write these types of tests and also how they differ from our unit/integration tests. More in the PR.
Signed-off-by: morsak <xorsak02@stud.fit.vutbr.cz>

[MO] - [blog post] -> introduction to system tests

---

_posts/2020-10-01-hacktoberfest.md

Signed-off-by: Simon Woodman <swoodman@redhat.com>

Minor language fixes

---

_posts/2020-09-29-strimzi-survey-results.md

Reword a couple of sentences

---

_includes/documentation/documentation-version-band.html
_posts/2020-10-02-producer-tuning.md
_posts/2020-10-15-producer-tuning.md
docs/operators/master/deploying.md

Signed-off-by: prmellor <pmellor@redhat.com>
New post to describe the configuration properties to use for producer optimization

Blog post for producer tuning

---

docs/operators/0.20.0/contributing-book.html
docs/operators/0.20.0/deploying-book.html
docs/operators/0.20.0/full/contributing.html
docs/operators/0.20.0/full/deploying.html
docs/operators/0.20.0/full/overview.html
docs/operators/0.20.0/full/quickstart.html
docs/operators/0.20.0/full/using.html
docs/operators/0.20.0/overview-book.html
docs/operators/0.20.0/using-book.html
docs/operators/latest/contributing-book.html
docs/operators/latest/deploying-book.html
docs/operators/latest/full/contributing.html
docs/operators/latest/full/deploying.html
docs/operators/latest/full/overview.html
docs/operators/latest/full/quickstart.html
docs/operators/latest/full/using.html
docs/operators/latest/overview-book.html
docs/operators/latest/using-book.html

We have done a lot of smaller bug fixes to the documentation after the 0.20.0 release. This Pr updates the documentation on the website to contain them as well.

Update the 0.20.0 docs with the post release bugfixes

---

_data/authors.yml
_posts/2021-03-29-connector-build.md

Signed-off-by: Jakub Stejskal <xstejs24@gmail.com>

Address several comments for connect-build after merge

---

_posts/2021-11-07-canary.md

This PR is about a blog post related to an introduction on the new canary component.

Canary blog post

---

_includes/join-us/join-us-contribute-to-strimzi-band.html

Connected Youtube Links on Join Us page

---

_data/releases.yaml
docs/bridge/0.21.2/0.21.2.html
docs/bridge/0.21.2/full.html
docs/bridge/0.21.2/images/README
docs/bridge/0.21.2/index.md

Add documentation and release for bridge 0.21.2

Add Strimzi Kafka Bridge 0.21.2 to the website

---

_data/presentations.yaml

This PR adds some of my videos and conference talks to the website.

Add some of my presentations, videos and conference talks to the Strimzi website

---

_data/presentations.yaml

This PR adds some more presentations that use Strimzi.

Added some more sessions

---

_posts/2021-11-07-canary.md

Fix broken link in canary blog entry

---

_posts/2022-05-20-what-is-new-in-strimzi-0.29.0.md

Given the lack of new blog posts lately, I think it might be good to add the _What's new in Strimzi 0.29.0_ video as a blog post as well.

Add blog post with the What's new in Strimzi 0.29.0 video

---

_data/presentations.yaml
_posts/2022-05-23-StrimziPodSets-what-it-is-and-why-should-you-care.md

This PR adds a blog post for the _StrimziPodSets - What it is and why should you care?_ video to have it listed on the website as well. It also adds it to the presentation list.

Add blog post with the StrimziPodSets video

---

_data/presentations.yaml
_posts/2022-05-26-zookeeper-less-kafka-in-strimzi-0.29.md

As with the previous PRs, this PR adds a new _video_ blog post about the KRaft video which is planned to be published tomorrow.

Add video blog post about KRaft

---

_includes/homepage/homepage-announcement-band.html
_layouts/index.html

Add a link to the 2022 survey to the site header
[* ] Typo/minor fix

Added Survey link to header

---

_posts/2022-07-27-what-is-new-in-strimzi-0.30.0.md

When releasing the 0.30.0, I forgot to add a blog post with the _What's new in Strimzi 0.30.0_ video. So at least addiitonally, to have it propagate to RSS readers etc., this PR adds it.

What's new in Strimzi 0.30.0 blog post

---

_posts/2022-10-05-doc-feedback.md

Signed-off-by: prmellor <pmellor@redhat.com>
**Blog**
Adds a blog post providing information on documentation feedback

docs(blog): Documentation feedback

---

_includes/documentation/documentation-version-band.html

Signed-off-by: prmellor <pmellor@redhat.com>

website(docs): Adds a link to contributor page from the latest documentation page

---

_data/releases.yaml
_includes/documentation/documentation-version-band.html

Link title change on documentation page

Docs link title change

---

_posts/2023-01-25-what-is-new-in-strimzi-0.33.0.md

This PR adds the _What's new in Strimzi 0.33.0_ video to the website as a blog post to have it there and get it to RSS readers.

Add `What's new in Strimzi 0.33.0` video to the website as blog post

---

charts/index.yaml

This PR adds the Drain cleaner 0.4.0 Helm Chart to the index on the website.

Add Drain Cleaner 0.4.0 to the Helm Chart index

---

charts/index.yaml

This PR updates the Helm Chart index and adds Drain Cleaner 0.4.2 to it.

Add Drain Cleaner 0.4.2 to the Helm repository on our website

---

_includes/homepage/homepage-usedby-band.html

This PR just changes the alignment of the logos of the "Used by" companies on the website.

Center the logo on the website

---

_sass/core/global.scss

**Web page**
CSS introduced for the docs was affecting the downloads page
Removed

docs(css): removes css that was affecting downloads page

---

_includes/documentation/documentation-version-band.html
contributing/guide/index.md
docs/operators/in-development/configuring.md
docs/operators/in-development/contributing.md
docs/operators/in-development/deploying.md
docs/operators/in-development/overview.md
docs/operators/latest/overview.md

**Documentation change**
Updates the titles for the in-development guides on the documentation page based on the latest changes

docs(titles): updates the titles for the in-development docs to reflect latest

---

charts/index.yaml

This PR adds Drain Cleaner 0.5.0 Helm Chart to the Helm Cart index.

Add Drain Cleaner 0.5.0 Helm Chart to the Helm Chart index

---

_posts/2023-08-14-kafka-node-pools-introduction.md
_posts/2023-08-23-kafka-node-pools-node-id-management.md
_posts/2023-08-28-kafka-node-pools-storage-and-scheduling.md
_posts/2023-09-11-kafka-node-pools-supporting-kraft.md

A link at the end of the blog post encourages the reader to go straight to the next one in the series.

Add links to the end of the node pools blog posts

---

charts/index.yaml

This PR adds the Drain Cleaner 1.0.0 Helm Chart to the Helm Chart index.yaml on our website.

Add Drain Cleaner 1.0.0 to the Helm Chart index on our website

---

_includes/quickstarts/create-commands.md

This PR makes the outcome of the consumer/producer example in the [quickstart](https://strimzi.io/quickstarts/) explicit.

Making produce/consume example outcome explicit

---

_data/presentations.yaml

This PR adds the recording of my "Make Your Kafka Cluster Production-ready" talk from DoK Day / KubeCon NA 2023 to the presentations.

Add "Make Your Kafka Cluster Production-ready" talk from DoK Day / KubeCon NA 2023

---

_includes/site-header.html
_layouts/default.html
_sass/core/global.scss
_sass/includes/toc.scss
_sass/strimzi.scss
assets/css/main.scss

**Updates to doc web pages**
- Removes the resizeable ToC
- Adds a new ToC switch to turn the ToC on/off
- Reduces the size of the ToC text to put more titles on a single line
- Adds a dynamic "Top" button (mainly for mobile views to return to the ToC)
- Sets a more readable weight to the text

docs(web pages): updates to the ToC and general navigation improvements

---

_posts/2024-01-03-prevent-broker-scale-down-if-containing-paritition-replicas.md

This PR fixes the `author` field in the last blog post to have it correctly listed on the website.

Fix author of Shubham's blog post

---

_sass/includes/toc.scss

**website download page**
Fixes table format issue on download page

docs(fix): fixes doc table format issue on downloads page

---

_includes/homepage/homepage-usedby-band.html
_sass/strimzi.scss

This PR tries to improve the aligment of the company logos discussed in #410 and improve the visibility of the title.

Improve aligment of the logos of user companies

---

_includes/homepage/homepage-usedby-band.html

This Pr updates the project status on the website to incubating.

Update project status to incubating

---

_includes/homepage/homepage-announcement-band.html
_layouts/index.html

Add banner to highlight StrimiCon CFP

---

_posts/2024-03-19-what-is-new-in-strimzi-0.40.0.md

When doing the 0.40.0 release, I forgot to add the _What's new_ video to the blog posts. This PR adds it there.

What's new in Strimzi 0.40.0

---

_includes/homepage/homepage-announcement-band.html
_layouts/index.html

Remove StrimziCon banner

---

_data/authors.yml
_posts/2024-06-06-strimzicon2024-roundup.md

StrimziCon roundup blogpost

---

_includes/homepage/homepage-hero-band.html

This Pr updates the Intro video on the website homepage. (The video itself was created by @katheris)

Update Intro video on the website

---

_posts/2024-10-24-autorebalancing-on-scaling.md
_posts/2024-11-25-autorebalancing-on-scaling.md

This PR adds a new blog post about the auto-rebalancing on scaling feature coming in the next Strimzi 0.44.0.

Added blog post about auto-rebalancing on scaling feature

---

_posts/2024-11-25-autorebalancing-on-scaling.md

This Pr fixes the embedded video in @ppatierno's blog post.

Fix embedded YouTube video

---

_sass/includes/strimzi_navigation.scss
_sass/includes/toc.scss

Attempt at fixing 
> 1. Decrease the header height
> 2. Moving the Strimzi logo to the right or left side of the header instead of placing it above the header links
> 3. Reduce the size or remove the orange arrow at the bottom of the selected link
from strimzi/strimzi-kafka-operator#10782

#10782 refactor spacing in the header

---

_data/presentations.yaml

This PR adds the Strimzi KubeCon talks to the list of presentations.

Add the KubeCon talks to the list of presentations

---

_includes/homepage/homepage-announcement-band.html
_layouts/index.html

Trivial PR to add a banner on the website about the StrimziCon 2025 CFP.

Added StrimziCon 2025 CFP banner

---

charts/index.yaml

This PR adds Drain Cleaner 1.3.0 to the Helm chart index

Add Drain Cleaner 1.3.0 to the Helm Chart index

---

_includes/homepage/homepage-announcement-band.html
_layouts/index.html

This PR adds a banner on the Strimzi website about registration for StrimziCon 2025.

Added banner for StrimziCon 2025 registration

---

_posts/2025-05-04-what-is-new-in-strimzi-0.46.0.md

This PR adds the blog post with the "What's new in Strimzi 0.46.0" video.

Added blog post about the What's new in Strimzi 0.46.0 video

---

_posts/2025-04-16-strimzicon2025-schedule.md

Trivial PR to change the order of Apple speakers as requested.

Fixed order Apple speakers

---

_data/presentations.yaml

This PR adds presentations from KubeCon Europe 2025 and Current London 2025.

Added presentations at KubeCon Europe 2025 and Current London 2025

---

_data/authors.yml
_posts/2025-09-05-monitoring-of-custom-resources.md
_posts/2025-10-01-monitoring-of-custom-resources.md

Part of https://github.com/strimzi/proposals/blob/main/087-monitoring-of-custom-resources.md
Related to the upcoming release 0.48.0.

Blog Post: Custom Resource Monitoring
