_data/menu.yml
documentation/index.md
downloads/index.md
index.md

Related to strimzi/strimzi#356, this PR creates two new sub-pages Downloads and Documentation. These pages will contain all links to all versions of Strimzi. On the main page, we would keep only the latest release + documentation for master. WDYT?

Hide older downloads and documentation from the main page

---

_includes/header.html
downloads/index.md
index.md

This PR updates the links to the GitHub repository to avid unnecessary redirects. It doesn't update all links - for example links in older blog posts remain unchanged (the links still work). It renames just the main sites.

Update links to GitHub repository to avoid unnecessary redirects

---

_data/menu.yml
contributing/index.md
index.md

This PR adds dedicated _Contributing_ page and links to it from the menu as well as from the index page. It contains the original content of the _Contributing_ section from the main page enhanced with documentation contributions.

Add Contributing page

---

README.md
charts/index.yaml

Add Helm Chart repository index.yaml with valid previous chart releases.
See project PR for more details: https://github.com/strimzi/strimzi-kafka-operator/pull/801

Add initial Helm Chart repository

---

_data/menu.yml
index.md
quickstarts/index.md
quickstarts/minikube/index.md
quickstarts/okd/index.md

Discussion:
a set of quickstarts, covering `minikube` and OKD (`oc cluster up`).
Uses simple, vanilla Strimzi - no extra feature (e.g. exposure)

First set of quickstarts (OKD and minikube)

---

_includes/footer.html
_includes/header.html

Also use https links when external sites redirect http to https anyway.

Use https when pulling images from other domains.

---

quickstarts/minikube/index.md
quickstarts/okd/index.md

The Quickstarts are not making it clear how to send or receive messages. I added a new chapter about this. It is basically a copy of the corresponding section from the docs.

Add message producer and consumer to the Quickstarts

---

quickstarts/minikube/index.md

The current quickstart fails when sending/receiving messages due to not specifying the correct namespace, specify it in the kubectl invocation.

Update minikube example send/receive using kafka namespace

---

_posts/2019-03-07-strimzi-0.11.0-release.md

This gets rid of the warning
Liquid Warning: Liquid syntax error (line 167): Unexpected character $ in "{{ $value }}" in /home/tom/messaging/strimzi.github.io/_posts/2019-03-07-strimzi-0.11.0-release.md
from Jekyll

Use {% raw %} to prevent Liquid/Jekyll warning

---

quickstarts/minikube/index.md

Addresses failure to start Kakfa producer.
```Normal   Scheduled  7m21s  default-scheduler        Successfully assigned kafka/kafka-producer to docker-desktop
Normal   Pulling    7m18s  kubelet, docker-desktop  Pulling image "strimzi/kafka0.12.1-kafka-2.2.1"
Warning  Failed     7m18s  kubelet, docker-desktop  Failed to pull image "strimzi/kafka0.12.1-kafka-2.2.1": rpc error: code = Unknown desc = Error response from daemon: pull access denied for strimzi/kafka0.12.1-kafka-2.2.1, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Warning  Failed     7m18s  kubelet, docker-desktop  Error: ErrImagePull
```

Fix producer example image typo

---

_posts/2019-07-22-http-bridge-intro.md

This blog post is an introduction about the HTTP - Kafka bridge which could be followed by at least another article with a step by step example of producing and consuming messages with it.

Introduction to the HTTP - Kafka bridge blog post

---

quickstarts/minikube/index.md
quickstarts/okd/index.md

This PR:
* Uses `kubectl wait` instead of instructions to watch pods
* Puts `-n namespace` option in a consistent place
* Clarifies running producer and consumer in different terminals

Tinker with quickstarts

---

quickstarts/okd/index.md

The producer and receiver commands use the kafka namespace, while the kafka cluster in created in myproject namespace. I edited the producer and consumer commands replacing the kafka namespace with myproject.

Wrong namespace in the commands to run receiver and producer

---

quickstarts/minikube/index.md
quickstarts/okd/index.md

This PR fixes the `wait` command in the OKD quickstart and change the parameters order to follow the command help where the resource is provided before the options with "for conditions".

Fixes on wait command in the quickstarts

---

contributing/index.md
index.md

This PR upúdates the mailing list and Slack links to the new CNCF hosted links.

Update links to mailing lists and Slack

---

docs/0.14.0/0.14.0.html
docs/0.14.0/full.html
docs/latest/full.html
docs/latest/latest.html

It seems that due to some misprocessing our 0.14.0 docs refer to the latest version on many places. This PR should fix it. This was probably uman error and not system issue with the build system.

Fix version in 0.14.0 documentation

---

_posts/2019-10-08-strimzi-apache-kafka-and-tracing.md

There seems to be a small typo in the Tracing blog post. This PR should fix it.

Fix typo in the tracing blog post

---

_config.yml
_redirects

Use Netlify redirects to create a simple URL to our installation files - somthing like `https://strimzi.io/install` to redirect to the single YAML installation.

Use Netlify redirects to create a simple URL to our installation files

---

quickstarts/minikube/index.md

Fixes strimzi/strimzi-kafka-operator#2138

Use 4G memory in minikube quickstart.

---

_posts/2019-11-05-exposing-http-bridge.md

The link in our last HTTP blog post is broken. This PR fixes it.

Fix wrong link in HTTP Bridge blog post

---

_data/releases.yaml
documentation/archive/index.md

The documentation archive doesnt currently contain links to the new Overview and Quick Start books added in new releases. This Pr tries to fix that.

Fix documentation archive to support multiple books

---

_posts/2019-11-05-exposing-http-bridge.md

This PR fixes the typo in the HTTP Bridge blog post which was reported on Slack (https://cloud-native.slack.com/archives/CMH3Q3SNP/p1581290373448700)

Fix typo in HTTP Bridge blog post

---

_redirects

The redirect to the latst installation file has a typo in it and doesn't work. This PR fixes it.

Fix typo in redirect file

---

quickstarts/kind.md
quickstarts/quickstarts-tabs.html

During the website upgrade, we lost the Kubernetes Kind quickstart. This Pr adds it back and also renames the tabs in the quickstart section.

Add back the Kind quickstart which was lost during the new website upgrade

---

_includes/share-page.html
_layouts/post.html
_sass/includes/share-page.scss

This PR is for addressing #25 and adds the share buttons on the blog posts. A lot of the code and images were already in the repo, so enabled it and fine-tuned.
- Updated share-page.html to use correct variables.
- Added the share-page include to posts.html.
- Fixed CSS for outlining.
It looks like this:

Added blog sharing buttons

---

_redirects

The URLs of the blog posts changed on the new website. This Pr tries to add redirects to make sure the old URLS forward to the new ones.

Add redirects for old blog post URLs

---

_includes/homepage/homepage-usedby-band.html

The KubeCon banner currently points to KubeCon NA. We should have it pointing to KubeCon Europe which will be first.

Change the KubeCon banner to Europe and not to North America

---

_redirects

This adds redirects to the old Quick Starts links which might be still somewhere listed. Related to strimzi/strimzi-kafka-operator#2889

Add redirects for Quick Starts guides

---

_includes/site-header.html
_layouts/default.html
docs/bridge/latest/index.md
docs/latest/index.md
docs/overview/latest/index.md
docs/quickstart/latest/index.md

Currently, in the latest docs, we do not say for whcih version they apply. we just say _Latest_ or _Latest stable_. That could be confusing - while we know which version is the latest, the users might not. This PR replaces the _latest_ with the actual version number to mke it easier for users.

Make it clear in the latest docs wfor which version they apply

---

_posts/2019-10-14-improving-prometheus-metrics.md

Some time ago we moved the metrics from the `metrics` folder to `examples/metrics`. This PR fixes an older blog post which is now refering to wrog location and confusing users.

Fix brokern links in the Prometheus blog post

---

_includes/homepage/homepage-content-band.html

As per https://github.com/strimzi/strimzi-kafka-operator/blob/master/design/github-repository-restructuring.md., the project roadmap is now moved from a GitHub project in the strimzi-kafka-operators repository to the Stirmzi GitHUb organization: https://github.com/orgs/strimzi/projects/1
This PR changes the link to the roadmap on the website to make it in sync.

Move the project roadmap

---

_posts/2019-05-13-accessing-kafka-part-4.md

The Accessing Kafka blog post - part about load balancers has a misaligned fields in one of the examples. This PR fixes the alignment.

Fix typo in one of the example codes in the Accessing Kafka blog post

---

_includes/homepage/homepage-usedby-band.html

The KubeCon banner on the website has old date and wrong location. This PR fixes it.

Update KubeCon date and location

---

_posts/2020-07-21-tips-and-tricks-for-running-strimzi-with-kubectl.md
_posts/2020-07-22-tips-and-tricks-for-running-strimzi-with-kubectl.md

This PR adds a new blog post with some tips & tricks how Strimzi can be used with `kubectl` - short names, categories, json path etc.

Add new blog post about kubectl tips & tricks

---

_includes/homepage/homepage-announcement-band.html
_layouts/index.html

This PR removes the Strimzi survey band. I preferred to not delete the related HTML file but to comment the content in order to have it ready as a placeholder when we have to do another announcement; I preferred this compared to comment the "include" in the home as well.

Removed Strimzi survey band

---

_posts/2020-09-29-strimzi-survey-results.md
_posts/2020-10-01-hacktoberfest.md

Just noticed that the latest two blog posts don't show authors names because of the wrong id related to the authors YAML file.

Fixed authors on latest blog posts

---

_includes/documentation/documentation-version-band.html
quickstarts/kind.md
quickstarts/minikube.md
quickstarts/okd.md

This PR does two things, based on some of the feedback from the survey:
1. It explicitly gives people some suggested things to read next at the end of the quickstart.
2. It adds a link to the custom resource examples to the documentation page.

Links to examples; signpost where next after quickstart

---

_sass/strimzi.scss

On the main page, I found out that the `zoom_band` section is not handled on mobile and tablet screens properly. The fix on the main page is in adding extra media queries in the section.
On blog post pages the long string wrapped in the `code` tag is not split which causes that the issue. Adding a CSS style of `break-word` fixes the issue there.
I also updated a bit of styling in the `_sass/strimzi.scss` file.
Closes #190

Add style to remove extra white space on tablet and mobile screens

---

_includes/documentation/documentation-archive-band.html
_includes/documentation/documentation-version-band.html
docs/operators/0.18.0/deploying.md
docs/operators/0.19.0/deploying.md
docs/operators/0.20.0/deploying.md
docs/operators/latest/deploying.md
docs/operators/master/deploying.md

The _Deploying_ guide also contains the upgrade documentation. Therefore @PaulRMellor suggested to call it _Deploying and Upgrading_ guide to make it easier for users to find the upgrade docs. This PR renames the docs on our website to match that.

Rename Deploying guide to Deploying and Upgrading

---

_posts/2020-11-10-dynamically-changeable-logging.md

Signed-off-by: Stanislav Knot <sknot@redhat.com>
I am sorry. There is an indentation error in the Dynamic logging blogpost.

Fix indentation in logging BP

---

_includes/downloads/downloads-release-band.html

This PR fixes the broken download links in for Helm Charts in the Downloads section.

Fix download links for Helm Charts

---

_data/releases.yaml
_includes/downloads/supported-versions-band.html
_layouts/downloads.html
_sass/core/includes/supported-versions-band.scss
_sass/includes/supported-versions-band.scss
assets/css/main.scss

Following the idea from the _Meet the Maintainers_ session, this PR drafts how a new section on the downloads page might look like (content is just dummy right now). Please have a look and let me know what do you think.
I guess other alternative would be to have a separate page with the versions table and only link it from the downloads page.

Add new section to Download page with supported versions of the different components

---

_includes/downloads/supported-versions-band.html

This PR does a slight improvement to #209 and adds link to the corresponding Bridge and OAuth releases into the table.

Add more links to the supported versions table

---

quickstarts/kind.md
quickstarts/minikube.md
quickstarts/okd.md

The Quickstarts on our website currently tell users to run the images `strimzi/kafka:...` without using the full path with the container registry. This PR changes that to use the `quay.io/` prefix.

Fix image name in Quickstarts

---

_includes/homepage/homepage-content-band.html
_includes/homepage/homepage-hero-band.html

While working on the Strimzi Datasheet I noticed some typos and wrong capitalization on the homepage. This Pr tries to fix some of them.

Fix some typos on the Stirmzi website homepage

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
GOVERNANCE.md
MAINTAINERS.md
_includes/documentation/documentation-version-band.html
charts/index.yaml
contributing/index.md

This PR updates the build in this repository so that we can rename the `master` branch to `main`.

Prepare build to rename master branch to main

---

_posts/2019-04-23-accessing-kafka-part-2.md
_posts/2019-04-30-accessing-kafka-part-3.md
_posts/2019-05-13-accessing-kafka-part-4.md
_posts/2019-05-23-accessing-kafka-part-5.md

It looks like lot of people still use the _Accessing Kafka_ blog post series. But the YAML examples it contains are not supported anymore. This PR adds additional examples to them using the new APIs.

Add new API examples to Accessing Kafka blog posts

---

_sass/includes/project-footer.scss
_sass/includes/strimzi_navigation.scss
_sass/strimzi.scss

This pull request is a fix for the inconsistent link color behaviour #218.
Changes per component:
- Menu: icon links (GitHub, Twitter and YouTube) now also change color on hover event.
- Footer: icon links (GitHub, Twitter and YouTube) label also trigger child element `<i>` to change color on hover event.
- Project/global: moved the hover event after the visited event styling, so that hover event styling ranks higher. Also made link color `!important`, because this is used throughout the styling.
Menu icons now have color applied on hover event.
Footer icon and label color applied on label hover event.
Other links are now working as well.
I noticed some improvements and refactoring we can do in the .scss files, will create some GitHub issues for these. For example, removing the …

Fixed inconsistent link color behaviour

---

_redirects

The URL shortcut for example files through `https://strimzi.io/examples/latest/...` currently points to wrong set of examples. This is due to the move between `example/` and `packaging/examples/`. This PR fixes it to point to the examples to the right place for the `v1beta2` examples.

Fix the URL in the examples redirect

---

_includes/documentation/documentation-archive-band.html
_includes/documentation/documentation-version-band.html
_sass/core/includes/secondary-page-title-band.scss
_sass/includes/download-archives-band.scss

Currently, the website has two versions of the documentation: one is embedded into the website it self:
* for example https://strimzi.io/docs/operators/latest/quickstart.html
Other one is using the default Asciidoc rendered:
* for example https://strimzi.io/docs/operators/latest/full/quickstart.html
To get to the other one, you need to know how to change the URL. But in some cases, the full documentation is more readable. So this PR adds new icons to the documentation website which can be used to directly open the _full_ documentation in a new window.
@strimzi/maintainers please have a look at this and let me know what do you think about it. You can also try it in the preview.

Add link to full docs

---

_posts/2020-06-05-cruise-control.md

This Pr fixes a small typo in the Cruise Control blog pot reported by a user on Slack: https://cloud-native.slack.com/archives/CMH3Q3SNP/p1619098604217700

Fix typo in Cruise Control blog post

---

_posts/2021-05-07-deploying-kafka-with-lets-encrypt-certificates.md

Signed-off-by: Simon Woodman <swoodman@redhat.com>
Great blog post but I think there is a copy/paste error in the Kafka CR example

Fix example broker numbering

---

_sass/core/global.scss
_sass/strimzi.scss

The text formatted as code seems to be using bigger font than the text around it (I guess technically it is not bigger, but it looks like it because of different font). This PR tries to fix the font size to make it look better.

Fix font size of code formatted text

---

_posts/2021-07-20-using-kubernetes-config-provider-to-load-data-from-secrets-and-config-maps.md
_posts/2021-07-22-using-kubernetes-config-provider-to-load-data-from-secrets-and-config-maps.md

This PR adds a new Blog Post about _Using Kubernetes Configuration Provider to load data from Secrets and Config Maps_.

Blog Post: Using Kubernetes Configuration Provider to load data from Secrets and Config Maps

---

_includes/downloads/downloads-release-band.html
_includes/downloads/downloads-title-band.html

The Download page in our website has a reference to Docker Hub which we no longer use:
This PR removes it completely from the sub-header. And instead adds link below the release table pointing to the Quay registry. Since the container images are not really usable on their own, I do not think they need to be pointed to in the sub-header:

Fix incorrect reference to Docker Hub

---

docs/operators/0.26.0/contributing-book.html
docs/operators/0.26.0/deploying-book.html
docs/operators/0.26.0/full/contributing.html
docs/operators/0.26.0/full/deploying.html
docs/operators/0.26.0/full/overview.html
docs/operators/0.26.0/full/quickstart.html
docs/operators/0.26.0/full/using.html
docs/operators/0.26.0/overview-book.html
docs/operators/0.26.0/using-book.html
docs/operators/latest/contributing-book.html
docs/operators/latest/deploying-book.html
docs/operators/latest/full/contributing.html
docs/operators/latest/full/deploying.html
docs/operators/latest/full/overview.html
docs/operators/latest/full/quickstart.html
docs/operators/latest/full/using.html
docs/operators/latest/overview-book.html
docs/operators/latest/using-book.html

It looks like the docs for the 0.26.0 release were rendered without the proper `ProductVersion` variable and use therefore on many places `latest` instead of `0.26.0`. This PR updates the docs with a properly rendered version.

Fix the version in the 0.26.0 docs

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

* Try to set expectations for people wanting to blog by defining a process. 
* Use a very basic PR template referencing the README (considered using [named PR template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository), but there's doesn't seem to be a way to have people say "this is a blog post PR" when opening a PR, just the `template` query parameter).

Define a blog post process

---

_posts/2021-12-14-strimzi-and-log4shell.md

This blog posts covers how is Strimzi affected by the Log4Shell vulnerability. It explains what parts are affected, mentions the similar issue in Log4j1 and covers the mitigations (ideally with upgrade, alternatively using the Java system property).

Blog post about how is Strimzi affected by Log4Shell / CVE-2021-44228

---

_posts/2021-12-17-kafka-segment-retention.md

This PR fixes the blog post about segments, rolling and retention.
Consumers (starting from beginning) still get messages from closed segments (open in read only mode) but not from ones with `.deleted` suffix and the actual deleted (because of course not on disk anymore).

Errata on segment, rolling and retention blog post

---

_posts/2021-12-14-strimzi-and-log4shell.md

With the 0.27.0 release out, I thought it would be useful to add a small note to the Log4j2 blog post since it fixes the additional Log4j2 CVEs.

Update the Log4j2 blog post with reference to the 0.27.0 release which fixes additional Log4j2 CVEs

---

_data/presentations.yaml

This PR adds the "Everything you ever needed to know about Kafka on Kubernetes but were afraid to ask" conference talk from Kafka Summit to presentations site.

Add "Everything you ever needed to know about Kafka on Kubernetes but were afraid to ask" talk to presentations

---

quickstarts/kind.md
quickstarts/minikube.md

The `--broker-list` option is all deprecated in kafka command line tools. We should use `--bootstrap-server` instead.

replace deprecated broker-list with bootstrap-server

---

_includes/homepage/homepage-usedby-band.html

This Pr improves the margin / spacing around the Atruvia logo to make it more similar to the other logos. The picture below shows the difference (left side is this PR, right side is the current website).

Improve the margin of the Atruvia logo

---

_data/releases.yaml
_includes/downloads/supported-versions-band.html

In the supported versions on the download page, we already list through footnote which Strimzi use the CRDs v1beta1 because it limits the Kubernetes support. This PR adds also the footnote about Kubernetes 1.25 and PodDisruptionBudgets `v1beta1`.

Add footnote about PDB v1beta1 requirement and Kubernetes 1.25 support

---

_data/presentations.yaml

This PR adds the links to my talk about social media analytics from Data on Kubernetes Day @ KubeCon to the list of presentations.

Add talk from DoK Day @ KubeCon about social media analytics to the presentations

---

_posts/2022-08-03-stimzi-based-infrastructure-as-a-java-code.md

This PR adds a new blog post about using the Strimzi `api` module / library. Any comments technical as well as language related are appreciated.

Blog post: Strimzi based Apache Kafka infrastructure as a Java code

---

_posts/2022-09-08-what-is-new-in-strimzi-0.31.0.md

This Pr adds the _What's new in Strimzi 0.31.0_ video to the blog post as we did with our previous releases. This should get it into the RSS readers etc.

Add What's new in Strimzi 0.31.0 video to the blog

---

_posts/2022-09-04-configuring-security-context-in-pods-managed-by-strimzi.md
_posts/2022-09-09-configuring-security-context-in-pods-managed-by-strimzi.md

This PR adds a blog post about the pluggable Pod Security Providers. This shouldbe published after the 0.31.0 release as a part of its promo.

Add blog post about `Configuring security context of Strimzi-managed pods`

---

charts/index.yaml

This PR adds the updated Helm Chart index with Strimzi 0.31.1 which was forgotten in #319.
This should close #320.
@strimzi/maintainers Please merge it after reviewing.

Add Helm Chart index file with Strimzi 0.31.1 to the website

---

_config.yml
_includes/header-navigation.html
_includes/project-footer.html

This trivial PR just replaces the unreadable link to the YouTube channel with the usage of the handle.

Using YouTube handle link instead of the not readable one

---

_includes/documentation/documentation-version-band.html

Signed-off-by: prmellor <pmellor@redhat.com>
Links using `{{site.github_url}}` had an additional `strimzi` in the path.
Removed

website(docs): Fixes links on documentation page

---

_data/presentations.yaml
_posts/2022-12-23-make-your-kafka-cluster-production-ready-local-storage.md

For better visibility, this PR adds the _Make your Kafka cluster production-ready: Local Storage_ YouTube video also as a blog post and to the presentations and videos section. This should also get it to the RSS readers and search engines.

Add the local storage video to the website as blog post and to the videos and presentations section

---

_posts/2023-01-22-auto-restarting-connectors.md
_posts/2023-01-25-auto-restarting-connectors.md

This is the second blog post related to the upcoming 0.33 release. It covers the connector auto-restart feature and should be released together with the release.

Add blog post about connector auto-restart feature

---

_includes/downloads/downloads-release-band.html

For whatever reason, we have on the Downloads page on the website a download link for the Helm 2 chart which we do not support for a long time. This PR removes it and instead adds a link to the CRDs YAML file.

Remove Helm 2 chart from the Downloads page

---

_posts/2020-11-10-dynamically-changeable-logging.md

This PR fixes a typo in the logging blog post which is using `=` instead of `:`.
This should close #358

Fix typo in logging blog post

---

_includes/header-navigation.html

We should add the orange highlight to the `Documentation` menu when the user is in the docs:

Highlight the `Documentation` menu when in docs

---

_sass/core/global.scss

**Documentation content update**
One or two of the tables in the docs overflow their container.
This PR adds adds CSS properties that adds a scroll bar to a table if the content overflows.
As far as I can see, this is only applicable to a couple of tables. 
See the following in the Configuring guide:
* Table 1. MirrorMaker 2 connector configuration properties
* KafkaClusterSpec schema properties
Fix type:

docs(tables): adds properties to control table content

---

_layouts/default.html

**Documentation content update**
One or two of the tables in the docs overflow their container.
This PR adds adds CSS properties that adds a scroll bar to a table if the content overflows.
Previously, this was set in the global CSS, which impacted the downloads page [#364]
As far as I can see, this is only applicable to a couple of tables.
See the following in the Configuring guide:
Table 1. MirrorMaker 2 connector configuration properties
KafkaClusterSpec schema properties

docs(tables): local properties to control large tables in the docs

---

_layouts/default.html
_sass/includes/toc.scss

**Docs pages**
Adds a control to allow resize of the Table of Contents by adding a resize handle to the scrollbar.
The width can be adjusted up to 40% or 0% to remove the ToC from display

docs(resize): adds resize to table of contents for docs

---

charts/index.yaml

This Pr fixes the incorrect URL in the Helm Chart index file.
This should resolve https://github.com/strimzi/drain-cleaner/issues/92

Fix incorrect URL in the Helm Chart index

---

_posts/2023-08-13-kafka-node-pools-introduction.md
_posts/2023-08-14-kafka-node-pools-introduction.md

This PR adds a new blog post about Kafka Node Pools. It is expected to be the first part of a blog post series, where the first part provides an introduction to the Kafka Node Pools. The next parts (which will have separate PRs) should cover management of the Node IDs, some situations around storage management where Node Pools might help and KRaft.

[Blog Post] Kafka Node Pools: Introduction

---

_posts/2023-08-14-kafka-node-pools-introduction.md
_posts/2023-08-19-kafka-node-pools-node-id-management.md
_posts/2023-08-23-kafka-node-pools-node-id-management.md

This PR adds the second part to the Kafka Node Pools blog post series, this time focused on Node ID management.

Kafka Node Pools: Node ID Management

---

_includes/toc.html
_layouts/default.html
_sass/core/global.scss
_sass/includes/toc.scss

**Docs web pages**
A few small changes to the presentation of the docs:
- Puts figure titles above diagrams
- Makes top-level ToC headings bold
- Uses 3 heading levels in ToC (removes unnumbered sections from)
- Removes discrete headings from ToC
- Adds _edit this page_ link to source docs files

docs(pages): docs presentation changes

---

_data/presentations.yaml

This PR adds recording and material links for the Strimzi presentation at the CNCF Napoli Cloud Native Community Group to the presentations section.

Added Strimzi presentation at CNCF Napoli community group

---

_posts/2023-12-06-where-is-Strimzi-1.0.0.md
_posts/2023-12-11-where-is-Strimzi-1.0.0.md

I feel like we should have some explanation why we are still using 0.x versions. So I put together this blog post that tries to explain it and also outline the next steps. Please have a look and let me know what you think ...

Where is Strimzi 1.0.0?

---

_layouts/default.html
_sass/includes/toc.scss

**Documentation content update**
Moves the style settings for large tables so that they are local and affect only documentation tables
The CSS properties  add a scroll bar to a table if the content overflows.
Previously, this was being set in the global CSS, which impacted the downloads page

docs(style): styles for large tables in the docs

---

charts/index.yaml

This PR adds the Drain Cleaner 1.1.0 to the Helm Chart index on the website.

Add Drain Cleaner 1.1.0 to the Helm chart index

---

_includes/homepage/homepage-announcement-band.html

As the StrimziCOn CfP is now closed, this PR replaces the call for papers banner ont he website with the call for registration.

Replace the StrimziCon CfP with call for registration

---

_sass/core/global.scss

- Fix
This PR fixes issue with the style of `<b>`/`<strong>` elements, as the text wasn't highlighted at all.
The reason is that the style of those two tags were overwritten by style of other "parent" elements -> `<p>`, `<ul>`, .etc.
For not inheriting the `font-weight` for `b, strong` elements, I added explicit style for them, which fixes the issue.
Before:
After:

Fix style for bold/strong text

---

_sass/strimzi.scss

- Minor fix
This PR adds configuration of `margin` and `padding` for announcement banner on mobile and tablet.
Before:
(mobile)
(tablet)
After:
(mobile)
(tablet)

Correct style for announcement on mobile and tablet

---

_data/presentations.yaml

This PR adds the KubeCon Europe 2024 talks to the presentation list.

Add KubeCon Europe 2024 talks

---

_posts/2024-04-08-strimzicon2024-schedule.md
_posts/2024-04-09-strimzicon2024-schedule.md

This PR adds a blog post about announcing the StrimziCon 2024 schedule.

Added blog post about StrimziCon 2024 schedule

---

_includes/quickstarts/create-commands.md
_includes/quickstarts/delete-commands.md

This PR updates the [Quickstarts](https://strimzi.io/quickstarts/) on our website to use KRaft instead of ZooKeeper based Kafka cluster. This should help to avoid the DNS issues related to ZooKeeper.

Use KRaft in the Quickstart example

---

_posts/2022-09-16-reassign-partitions.md

=> a simple typo (cf the line above or the reference doc: the attribute is called `mode`, not `model`)

Fix typo in _posts/2022-09-16-reassign-partitions.md

---

_includes/homepage/homepage-content-band.html

The old GitHub projects that we use for Readmap are being shutdown. So the Roadmap was migrated to the new Projects and the link changed. This PR updates the link in the README.md.

Update the link to Roadmap

---

charts/index.yaml

This PR adds Drain Cleaner 1.2.0 to the Helm Chart index on the website.

Add Drain Cleaner 1.2.0 to the Helm Chart index

---

_posts/2024-08-07-taming-apache-kafka-4.0.md
_posts/2024-08-21-taming-apache-kafka-4.0.md

This PR adds a new blog post about the Strimzi plans for Apache Kafka 4.0 support. It should give users a better idea of what to expect and when, while making sure there is still a large degree of uncertainty with regard to the release dates etc.

Taming Apache Kafka 4.0

---

_data/presentations.yaml
_includes/kraft/kraft-content.html
_includes/kraft/kraft-title-band.html
_layouts/kraft.html
kraft.md

This PR adds a new page dedicated to various information related to KRaft. The page is not directly linked anywhere. But it could be used for example in presentations or discussions to easily link to the blog posts, docs or videos. The preview of the page can be found here: https://deploy-preview-450--strimzi.netlify.app/kraft/
This PR also updates the list of presentations and conferences with some new talks.

Add dedicated KRaft page summarizing various KRaft related information

---

_data/presentations.yaml
_includes/kraft/kraft-content.html

This Pr adds the recording of my talk about ZooKeeper removal and KRaft from the Axual Kafka Meetup in Utrecht to the presentations and to the KRaft page (https://strimzi.io/kraft).

Add Kafka Meetup Utrecht recording to presentations and to list of KRaft sources

---

_posts/2024-09-26-managing-connector-offsets.md
_posts/2024-11-04-managing-connector-offsets.md

Blogpost: Managing connector offsets

---

_redirects
roadmap/index.md

Turns out, that we have the old Roadmap page on our website (https://strimzi.io/roadmap/), and still accessible through search engines. This PR replaces it with permanent redirect (HTTP 301).

Replace the old Roadmap page with redirect

---

_posts/2025-01-29-strimzicon2025-announcement.md

Trivial PR to update the blog post about StrimziCon 2025 because of a company move for one of the committee members.

Updated program committee member role on StrimziCon 2025

---

_includes/documentation/documentation-version-band.html

**Documentation page**
Fixes link to point to _full_ bridge doc

docs(docs): link fix for full bridge doc

---

_posts/2025-04-16-strimzicon2025-schedule.md

This PR adds a blog post related to the StrimziCon 2025 schedule announcement.

Added blog post about StrimziCon 2025 schedule

---

_includes/quickstarts/create-commands.md
docs/operators/0.46.0/deploying-book.html
docs/operators/0.46.0/full/deploying.html
docs/operators/latest/deploying-book.html
docs/operators/latest/full/deploying.html

With 0.46.0 update, it appears the `examples/kafka/kraft` folder from https://github.com/strimzi/strimzi-kafka-operator was removed.
This PR fixes the doc links for 0.46.0, in-development and latest folder from this repo.
Fixes https://github.com/strimzi/strimzi-kafka-operator/issues/11418

Fix strimzi/strimzi-kafka-operator#11418:  broken link to kraft with 0.46.0 update

---

_posts/2025-04-16-strimzicon2025-schedule.md

Unluckily, Apple folks won't be able to deliver the session anymore.
The Program Committee went through the other remaining sessions by ratings and picked the next one.
This PR adds the replacement session to the agenda.

Updated agenda with a session replacement

---

_includes/homepage/homepage-announcement-band.html
_layouts/index.html

This trivial PR removes the banner with the StrimziCon 2025 registration.

Removed banner for StrimziCon 2025 registration

---

_includes/quickstarts/create-commands.md
_includes/quickstarts/delete-commands.md
_includes/quickstarts/next-steps.md
quickstarts/dockerdesktop.md
quickstarts/kind.md
quickstarts/minikube.md

The heading levels in the Quickstarts are incorrectly used and render as many H1 headers in a single page. This PR tries to move them to a more suitable level.

Fix heading levels in Quickstarts

---

_data/presentations.yaml

This PR adds the link to the StrimziCon 2025 recordings playlist to the presentations section.

Added StrimziCon 2025 recordings playlist to the presentations

---

_includes/homepage/homepage-usedby-band.html
_sass/strimzi.scss

This PR completes the work done in https://github.com/strimzi/strimzi-kafka-operator/pull/11621 to the ADOPTERS.md file and splits also the company logos on the website to vendors and users. It also makes the logos smaller in general, to make it easier fit the website (and thus also easier to screenshot etc.)

Split users and vendors on the website

---

_posts/2025-10-01-monitoring-of-custom-resources.md

This tries to escape the YAML example where the website logix is replacing soma pers using double curly brackets. This should resolve #532.

Try to escape curly braces

---

_data/authors.yml
_posts/2025-08-26-strimzi-metrics-reporter.md
_posts/2025-10-06-strimzi-metrics-reporter.md

Related to the upcoming release 0.48.0.

Blog Post: Strimzi Metrics Reporter 
